---
- hosts: localhost
  connection: local
  tasks: # https://stackoverflow.com/questions/41535838
  - name: Update and upgrade apt packages 
    become: true
    apt:
      upgrade: 'yes' ## see https://serverfault.com/a/993211
      update_cache: yes
      cache_valid_time: 86400 #One day
  - name: install docker dependencies
    become: true # this is to become root
    package:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
  - name: Add an apt key by id from a keyserver
    become: true
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      keyring: /usr/share/keyrings/docker-archive-keyring.gpg
      state: present
  - name: get the arch
    shell: dpkg --print-architecture
    register: dArch
  - name: add apt repo
    become: true
    apt_repository:
      repo: deb [arch={{dArch.stdout}} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
      state: present
  - name: Update and upgrade apt packages again
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 8
  - name: install docker-ce
    become: true
    apt:
      name: docker-ce
      update_cache: yes
  - name: install docker-ce-cli
    become: true
    apt:
      name: docker-ce-cli
      update_cache: yes
  - name: install container
    become: true
    apt:
      name: containerd.io
      update_cache: yes
  - name: Register vars 1
    shell: uname -s
    register: unameS
  - name: Register vars 2
    shell: uname -m
    register: unameM
  - name: install docker compose
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ unameS.stdout }}-{{ unameM.stdout }}
      dest: /home/dmas/bin/docker-compose
      mode: 'u+x,g+x'

