---
- hosts: localhost
  connection: local
  tasks: # https://stackoverflow.com/questions/41535838
  - name: Update and upgrade apt packages 
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
  - name: install docker dependencies
    become: true # this is to become root
    package:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
  - name: Add an apt key by id from a keyserver
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: add apt repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
      state: present
  - name: install docker
    become: true
    package:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
  - name: Register vars 1
    shell: uname -s
    register: unameS
  - name: Register vars 2
    shell: uname -m
    register: unameM
  - name: install docker compose
    become: true
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ unameS.stdout }}-{{ unameM.stdout }}
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
