---
- hosts: localhost
  connection: local

  tasks: # https://stackoverflow.com/questions/41535838
  - name: Update and upgrade apt packages 
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: install packages
    become: true # this is to become root
    package:
      name:
        - htop
        - vim-nox
        - vim
        - tmux
        - dos2unix
        - neofetch
        - net-tools

  - name: copy vim conf file
    copy:
      src: dotfiles/vimrc
      dest: /home/dmas/.vimrc
      owner: dmas
      group: dmas

  - name: copy tmux conf file
    copy:
      src: dotfiles/tmux_29.conf
      dest: /home/dmas/.tmux.conf
      owner: dmas
      group: dmas

  - name: copy aliases conf file
    copy:
      src: dotfiles/bash_aliases
      dest: /home/dmas/.bash_aliases
      owner: dmas
      group: dmas

  - name: Creates projects directory
    file:
      path: /home/dmas/projects
      state: directory

  - name: Creates src directory
    file:
      path: /home/dmas/src
      state: directory

  - name: Creates bin directory
    file:
      path: /home/dmas/bin
      state: directory

  - name: clone custom scripts
    ansible.builtin.git:
      repo: 'https://github.com/davidmasp/custom-scripts.git'
      dest: /home/dmas/src/custom-scripts

  - name: Find all files in CS
    find:
      paths: /home/dmas/src/custom-scripts
      patterns: '*.sh,*.R,*.py'
    register: customS

  - name: Create symlinks to bin
    file:
      src: "{{ item.path }}"
      path: "/home/dmas/bin/{{ item.path | basename }}"
      state: link
    with_items: "{{ customS.files }}"

  - name: adds du usage cron job
    ansible.builtin.cron:
      name: "disk usage check"
      minute: "32"
      hour: "23"
      weekday: "6"
      job: "/home/dmas/bin/du_command.sh -t /home/dmas -o /home/dmas/.du_reports -d 2 -n 20"

### other ideas that I am not sure I want to dev yet
### 1) Install anaconda/miniconda through ansible
## mkdir home/dmas/src/anaconda
## https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
## sha256sum Miniconda3-latest-Linux-x86_64.sh
## then executing (it is interactive, worth it?)
### 2) download repo of curated self envs
